apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-risk-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-risk-api
  template:
    metadata:
      labels:
        app: credit-risk-api
    spec:
      containers:
      - name: api-container
        image: us-central1-docker.pkg.dev/true-sprite-459511-f5/credit-risk-repo/credit-risk-api:1756380348
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
